USE STAGE
GO

DROP TABLE IF EXISTS STAGE.MOVIE_UP_COMING
CREATE TABLE STAGE.MOVIE_UP_COMING
(
DT_PERIODO VARCHAR(8000),
ID VARCHAR(8000),
TITLE VARCHAR(8000)
)


DROP TABLE IF EXISTS STAGE.MOVIE_NOW_PLAYING
CREATE TABLE STAGE.MOVIE_NOW_PLAYING
(
DT_PERIODO VARCHAR(8000),
ID VARCHAR(8000),
TITLE VARCHAR(8000)
)


DROP TABLE IF EXISTS STAGE.MOVIE_RELEASES
CREATE TABLE STAGE.MOVIE_RELEASES
(
DT_PERIODO VARCHAR(8000),
ID VARCHAR(8000),
TITLE VARCHAR(8000)
)

DROP TABLE IF EXISTS STAGE.MOVIE_DETAIL
CREATE TABLE STAGE.MOVIE_DETAIL
(
ID VARCHAR(8000),
ORI_LANGUAGE VARCHAR(8000),
ORI_TITLE VARCHAR(8000),
POPULARITY VARCHAR(8000),
STATUS  VARCHAR(8000),
RUNTIME VARCHAR(8000),
REVENUE VARCHAR(8000),
BUGDET VARCHAR(8000),
VOTE_AVG VARCHAR(8000),
VOTE_CNT VARCHAR(8000)
)

DROP TABLE IF EXISTS STAGE.MOVIE_DETAIL_PRODUCTION
CREATE TABLE STAGE.MOVIE_DETAIL_PRODUCTION
(
ID VARCHAR(8000),
PRODUCTION_COMPANIES_ID VARCHAR(8000),
PRODUCTION_COMPANIES_NAME VARCHAR(8000),
PRODUCTION_COMPANIES_ORIGIN_COUNTRY VARCHAR(8000)
)


DROP TABLE IF EXISTS STAGE.MOVIE_DETAIL_GENRE
CREATE TABLE STAGE.MOVIE_DETAIL_GENRE
(
ID VARCHAR(8000),
GENRE_ID VARCHAR(8000),
GENRE_NAME VARCHAR(8000)
)


DROP TABLE IF EXISTS STAGE.MOVIE_DETAIL_COUNTRY
CREATE TABLE STAGE.MOVIE_DETAIL_COUNTRY
(
ID VARCHAR(8000),
ISO_3166_1 VARCHAR(8000),
NAME VARCHAR(8000)
)

----


DROP TABLE IF EXISTS STAGE.MOVIES_RELEASES_STATUS
CREATE TABLE STAGE.MOVIES_RELEASES_STATUS
(
DT_PERIODO INT,
ID INT,
TITLE VARCHAR(8000),
STATUS_MOVIE	VARCHAR(8000),
ISO_3166_1				VARCHAR(8000),
GENRE_ID				INT,
PRODUCTION_COMPANIES_ID	INT,
POPULARITY	FLOAT,
RUNTIME		INT,
REVENUE		FLOAT,
BUDGET		FLOAT,
VOTE_AVG	FLOAT,
VOTE_CNT	FLOAT
)


DROP TABLE IF EXISTS STAGE.PERIOD
CREATE TABLE STAGE.PERIOD
(
PERIOD INT,
PERIOD_MONTH_YEAR INT,
PERIOD_MONTH INT,
PERIOD_YEAR INT,
)


 
